---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-chart
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: master
  url: https://github.com/MOUAK-Ayoub/spring_batch_eks.git
