---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: demo-from-git
  namespace: default
spec:
  chart:
    spec:
      chart: ./k8s/demo
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: demo-chart
  interval: 1m0s
